version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/api
hooks:
# During the ApplicationStart deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ApplicationStart:
    - location: app-start.sh    
      timeout: 300
      runas: ec2-user
