server:
  port: 9001
spring:
  application:
    name: admin-skill-api-aws
  main:
    allow-bean-definition-overriding: true

memcached.cache:
    servers: engineer-skill-profiles-cache.atqko2.cfg.use2.cache.amazonaws.com:11211
    provider: aws
    operation-timeout: 60s
      
        
activemq:
  broker:
    url: ssl://b-10b219cf-832c-4548-b472-e864376cceb1-1.mq.us-east-2.amazonaws.com:61617
  user: engineerskillprofileuser
  password: engineerskillprofileuserpassword


amazon:
  region: us-east-2
  access:
    key: AKIAY2YPA44KKPI5IA5Q 
    secretkey: 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
    
aws:
  accessKeyId: AKIAY2YPA44KKPI5IA5Q
  secretKey: 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

