server:
  port: 9001
spring:
  application:
    name: admin-skill-api-aws
  main:
    allow-bean-definition-overriding: true

memcached.cache:
    servers: engineer-skill-profiles-cache.atqko2.cfg.use2.cache.amazonaws.com:11211
    provider: aws
    operation-timeout: 60s
      
        
activemq:
  broker:
    url: ssl://b-df8fb5b3-36a9-49b7-b93e-6d53ed54f5dd-1.mq.us-east-2.amazonaws.com:61617
  user: 
  password: 


amazon:
  region: us-east-2
  access:
    key:  
    secretkey: 
    
aws:
  accessKeyId: 
  secretKey: 

