server:
  port: 9001
spring:
  application:
    name: admin-skill-api-aws
  main:
    allow-bean-definition-overriding: true

memcached.cache:
    servers: engineer-skill-profiles-cache.atqko2.cfg.use2.cache.amazonaws.com:11211
    provider: aws
    operation-timeout: 60s
      
        
activemq:
  broker:
    url: ssl://b-ba01a586-7461-44bd-9ca9-f067bcf62e95-1.mq.us-east-2.amazonaws.com:61617
  user: engineerskillprofileuser
  password: engineerskillprofileuserpassword


amazon:
  region: us-east-2
  access:
    key: AKIAY2YPA44KCSBVLHJK 
    secretkey: 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
    
aws:
  accessKeyId: AKIAY2YPA44KCSBVLHJK
  secretKey: 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

